### ISSUE TITLE
Make desktop version responsive

### ISSUE THREAD

**Issue by annika-philipp** [ShopBro-Team/ShopBro2.0-Web#12]

**Comment by rosie-b** [comment]
**Footer nav** 
- [ ] make centred 
- [ ] consistent button size 
- [ ] fix in banner at bottom of page
**Buttons**
- [ ] "Add" button text - vertically align
- [ ] "Add button size - set to one size (currently flexes with screen size, feels inconsistent with other buttons)
- [ ] "Edit" / "Delete" button size - make smaller so take up less screen / less of a focus
- [ ] "Edit" / "Delete" button colour - make softer colour so don't stand out as much as actual items / costs
- [ ] "Logout" button size - align to button on Dashboard and Settings view
- [ ] "Edit Budget" button position - put to side of progress bar for all screens iPad and upwards
- [ ] "Edit Budget" button size - make smaller so take up less screen / less of a focus
**Shopping List**
- [ ] "Shopping List" heading - put space between heading and actual list for screens iPad and upwards
- [ ] "Item" / "Cost" input fields - put in row for all screens iPad and upwards

**Comment by rosie-b** [comment]
Added the logout button to the nav bar, to save room on the screen for the shopping items instead. Realise this is more than just a desktop responsive type activity and in hindsight the above list should have been lots of small feature updates, not all one list. Sorry team!! Will do better next time 😸

**Comment by rosie-b** [comment]
Submitting pull request now. Definitely worth a fresh pair of eyes to make sure everything is working as it should.

**Comment by annika-philipp** [comment]
done
